name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 5'
    
jobs:
  IPQ60XX-OpenWrt:
    uses: ./.github/workflows/IPQ60XX-OpenWrt.yml

  IPQ807X-OpenWrt:
    uses: ./.github/workflows/IPQ807X-OpenWrt.yml

  Delete-Old-Workflows:
    uses: ./.github/workflows/Delete-Old-Workflows.yml
